### ISSUE TITLE
library support 

### ISSUE THREAD

**Issue by mukulyadav23** [Krowne/Libraries#3]
whatsapp version 2.21.12.21 (211221007) stable has been released but the library still is for beta version 2.21.12.21. it causing whatsapp crash at startup

**Comment by Krowne** [comment]
For a little over a week I have had my computer broken, because the hard
disk that contained the operating system and the source codes of the
applications were in it. Until the end of next week I will not be able to
reinstall the operating system and verify the integrity of the information
has not been corrupted.

Anyway, putting beta version is just a typo, the library is for that
version. So the closure of WhatsApp has nothing to do with it, it also
happens to me sometimes and as soon as I can I will see what it is due to.

Thanks for notifying.
